// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhwceogfiksavwktafep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxod2Nlb2dmaWtzYXZ3a3RhZmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDEyOTYsImV4cCI6MjA2NDA3NzI5Nn0._zSaUF4dVnqhnic8GHX67yv9NJfSEpwGl5-rtLrgu6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);